"""empty message

Revision ID: 18322332648d
Revises: 1fdaf27032f0
Create Date: 2019-10-06 15:58:17.648894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18322332648d'
down_revision = '1fdaf27032f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('request_name', sa.String(length=32), nullable=True),
    sa.Column('request_type', sa.String(length=32), nullable=True),
    sa.Column('request_start_time', sa.String(length=32), nullable=True),
    sa.Column('request_end_time', sa.String(length=32), nullable=True),
    sa.Column('request_days', sa.String(length=32), nullable=True),
    sa.Column('request_description', sa.Text(), nullable=True),
    sa.Column('request_phone', sa.String(length=32), nullable=True),
    sa.Column('request_status', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leave')
    # ### end Alembic commands ###
